server.port=8091
spring.application.name=produits-service

# Base de données PostgreSQL (dans Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/produitsdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Exécuter data.sql au démarrage
spring.sql.init.mode=always

# Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Swagger
springdoc.api-docs.path=/api-docs